### ISSUE TITLE
Tag/Addon development improvements

### ISSUE THREAD

**Issue by nebulousGirl** [anomalylabs/streams-platform#54]
I successfully created my first tag. I have a few thoughts on the current implementation.

I found that application addons are loaded from addons/application.reference/tags/tagname
So, I put my simple tag in the src folder.

I had defined my own namespace for my tag, and I got an **autoloading error because the namespace is hardcoded in the AddonLoader class**.

Then, I ventured to create a tag from a package, and I encountered the same namespace issue.

I put those 2 lines in my service provider:
``` php
app('streams.addon.binder')->register('tag', 'warn', dirname(__FILE__).'/../../addons/tags/warn');
app('events')->fire("streams::tags.registered");
```
The second line is necessary for the whole thing to work properly, but I don't think it should be there. **Maybe, the event firing should be in the AddonBinder and not in the AddonManager?**

**Comment by RyanThompson** [comment]
Let's talk about this a little more. I am going to implement this in some measure.

One thing I had a problem with personally is organization:

core/vendor/slug is not going to work because it's hard to decipher what's a module / plugin / etc. 

We could suffix with the type like core/vendor/slug_type and that's just ugly to me.. And we're still limiting naming. 

I was thinking core/type/vendor/slug would be a nice convention. It's obvious where the different types are and it's still following a PSR model for structure too - just we're still using type folders like "modules", "plugins", etc.

Thoughts?

cc; @obrignoni

**Comment by RyanThompson** [comment]
In the last example we'll get the information on what the addon type is from the composer file.

**Comment by RyanThompson** [comment]
As I get into this - I believe I HAVE TO ASSUME some kind of convention. Otherwise there is no automation.

Classically, in order to add a package you need to register it / its service provider in some way. Addons are automatic - if they are installed they register themselves. So I HAVE to be able to assume that there is an addon class at Streams\{vendor}\{addon_type}\{slug}\{slug}{addon_type}

Example: $addon = new \Streams\Anomaly\Distribution\Streams\StreamsDistribution;

This way I can look for similar service providers and boot / register the addon.

**Comment by RyanThompson** [comment]
Done. Still some wonkiness but I will fix it tomorrow (later today lol)
