### ISSUE TITLE
Ryan give us back the Pyro

### ISSUE THREAD

**Issue by Piterden** [anomalylabs/streams-platform#735]
Hi, my friend.

Old version was awesome! Just like old times, isn't it?

I'd been happy to turn time back. I really miss it and also miss you all guys.

**Comment by Pixney-William** [comment]
And i miss you!

**Comment by dwainscheeren** [comment]
Miss you too

**Comment by Pixney-William** [comment]
Maybe we should all get together?

**Comment by keevitaja** [comment]
@Piterden what's wrong with the current version?

**Comment by RyanThompson** [comment]
@Piterden hello old friend! Good to see you! What have you been up to? 

Join our Discord server man, I'd love to have you around more: https://streams.dev/discord

A lot has happened since we last talked and I am working on Pyro/Streams a lot these days, haha.

https://pyrocms.com/posts/laravel-streams-pyrocms-4

^ The goal: Pyro minus all the crap lol. Compiling, installers, overly complex architecture, etc. Lean and mean.
