### ISSUE TITLE
HrefGuesser

### ISSUE THREAD

**Issue by ramon-villain** [anomalylabs/streams-platform#94]
This class doesn't handle a url request like 'admin/users/roles/edit/2', so the create's case it's just appending the 'create' segment into url.

I was working with in_array and regex, to clean the 'edit/2', but there are other cases, like 'admin/users/roles/permissions/2' that should redirect to 'admin/users/roles/create'.

The better way is defining the attributes or modify the class?

**Comment by RyanThompson** [comment]
Ya - its been in mind to remedy this so you don't get that edit/2/create type stuff. I think the router action or active section could be used to explode / implode the segments instead of just appending for sure.

I think the request / explode / pop array until matching the action / add create to end of array / implode

Wanna take a whack at it?

**Comment by ramon-villain** [comment]
For now I'll PR the attributes. Wanna try this later.

**Comment by RyanThompson** [comment]
Working on this tonight!

**Comment by ramon-villain** [comment]
you're on fire. hahaha
sorry cannot get time to see this :(

**Comment by RyanThompson** [comment]
All better and MUCH simpler: https://github.com/anomalylabs/streams-platform/commit/358a157a9b83158d00a3429ac08ca61404dece60

**Comment by RyanThompson** [comment]
All good - its hard in these stages of new code to ask of others.
